# -*- coding: utf-8 -*-
"""Bosques Aleatorios Clasificación

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1igtIgMMdrhoNtulIxtHVr-9PkEqeEbP9
"""

### LIBRERIAS A UTILIZAR ###

#se importan las librerias a utilizar
from sklearn import datasets

### PREPARAR LA DATA ###

#importar los datos de la mismta libreria de scikit-learn
dataset = datasets.load_breast_cancer()
print(dataset)

### ENTENDIMIENTO DE LA DATA ###

#verifico la informacion contenida en el dataset
print('Informacion en el dataset:')
print(dataset.keys())
print()

#verifico las caracteristicas del dataset
print('Caracteristicas del dataset:')
print(dataset.DESCR)

#seleccionamos todas las columnas
X = dataset.data

#defino los datos correspondientes a las etiquetas
y = dataset.target

### IMPLEMENTACION DE BOSQUES ALEATORIOS CLASIFICACION ###

from sklearn.model_selection import train_test_split

#separo los datos de "train" en entrenamiendo y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#defino el algoritmo a utilizar
#bosque aleatorios
from sklearn.ensemble import RandomForestClassifier

algoritmo = RandomForestClassifier(n_estimators = 10, criterion='entropy')

#entreno el modelo
algoritmo.fit(X_train, y_train)

#realizo una prediccion
y_pred = algoritmo.predict(X_test)

#verifico la matriz de confusion
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#calculo la precision del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print('Precision del modelo:')
print(precision)