# -*- coding: utf-8 -*-
"""k vecinos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jP4cEPnuzNW6WqvF-oy5tO_zeqoKjBSg
"""

### LIBRERIAS A UTILIZAR ###

#se importan las librerias a utilizar 
from sklearn import datasets

### PREPARAR LA DATA ###

#importamos los datos de la misma lobreria de scikit-learn
dataset = datasets.load_breast_cancer()
print(dataset)

### ENTENDIMIENTO DE LA DATA ###

#verifico la informacion contenida en el dataset
print('Informacion contenida en el dataset')
print(dataset.keys())
print()

#verifico las caracteristicas del dataset
print('Caracteristicas del dataset:')
print(dataset.DESCR)

#seleccionamos todas la columnas
X = dataset.data

#defino los datos correspondientes a las etiquetas
y = dataset.target

### IMPLEMENTACION DE k VECINOS MAS CERCANOS ###

from sklearn.model_selection import train_test_split

#separo lod datos de "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#defino el algoritmo a utilizar

from sklearn.neighbors import KNeighborsClassifier

algoritmo = KNeighborsClassifier(n_neighbors= 5, metric= 'minkowski', p=2)

algoritmo.fit(X_train, y_train)

#realizo una prediccion
y_pred = algoritmo.predict(X_test)

#verifico la matriz de confisión
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión:')
print(matriz)

#calcule la precision del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print('Precision del modelo:')
print(precision)