# -*- coding: utf-8 -*-
"""Naive Bayes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1emQmp1sh1NeLfgBvH9kE0rOfyEcUKWEp
"""

### LIBRERIAS A UTILIZAR ###

#se importan la librerias a utilizar
from sklearn import datasets

### PREPARAR LA DATA ###

#importar los datos de la misma libreria de scikit-learn
dataset = datasets.load_breast_cancer()
print(dataset)

## ENTRENAMIENTO DE LA DATA ###

#verificar la informacion contenida en el dataset
print('Informacion del dataset:')
print(dataset.keys())
print()

#verificar las caracteristicas del dataset
print('Caracteristicas del dataset:')
print(dataset.DESCR)

#seleccionamos todas las columnas
X = dataset.data

#definir los datos correspondientes a las etiquetas
y = dataset.target

## IMPLEMENTACION DE NAIVE BAYES ###

from sklearn.model_selection import train_test_split

#separar los datos de "train" en entrenamiento y prueba para probar el algoritmo
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#defino el algoritmo a utilizar NAIVE BAYES
from sklearn.naive_bayes import GaussianNB

algoritmo = GaussianNB()

#entreno el modelo
algoritmo.fit(X_train, y_train)

#realizo una prediccion
y_pred = algoritmo.predict(X_test)

#verifico la matriz de confusion
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusion:')
print(matriz)

#calculo para la prediccion del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print('Precision del modelo:')
print(precision)