# -*- coding: utf-8 -*-
"""Maquinas Vectores de Soporte

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gCoOKI2SZ6olXDrad9KTng8dSqluWjpC
"""

### LIBRERIAS A UTILIZAR ###

#se importan las librerias a utilizar
from sklearn import datasets

### PREPARAR LA DATA ###

#importamos los datos de la misma libreria de scikit-learn
dataset = datasets.load_breast_cancer()
print(dataset)

### ENTENDIMIENTO DE LA DATA ###

#verifico la informacion contenida en el dataset
print('Informacion en el dataset:')
print(dataset.keys())
print()

#verifico las caracteristicas del dataset
print('Caracteristicas del dataset:')
print(dataset.DESCR)

#seleccionamos todas las columnas
X = dataset.data

#definimos los datos correspondiente a las etiquetas
y = dataset.target

### IMPLEMENTACION DE MAQUINAS VECTORES DE SOPORTE ###

from sklearn.model_selection import train_test_split

#separo los datos de "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

#defino el algoritmo a utilizar
from sklearn.svm import SVC
algoritmo = SVC(kernel = 'linear')

#entreno el modelo
algoritmo.fit(X_train, y_train)

#realizo una prediccion
y_pred = algoritmo.predict(X_test)

#verifico la matriz de confusion
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusion:')
print(matriz)

#calculo la precision del modelo
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print('Precision del modelo:')
print(precision)

